module Spor.Token.Size.LineHeight exposing (LineHeight, toFloat, heading, body)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs LineHeight, toFloat, heading, body
-}


{-| An opaque type representing a LineHeight value.
-}
type LineHeight =
    LineHeight Float

{-| Convert LineHeight into Float.
-}
toFloat : LineHeight -> Float
toFloat (LineHeight value) =
    value

{-| 
-}
heading : LineHeight
heading =
    LineHeight <| 1.333


{-| 
-}
body : LineHeight
body =
    LineHeight <| 1.333

