module Spor.Token.Size.Stroke exposing (Stroke, toCss, sm, md, lg)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Stroke, toCss, sm, md, lg
-}

import Css

{-| An opaque type representing a Stroke value.
-}
type Stroke =
    Stroke Css.Px

{-| Convert Stroke into Css.Px.
-}
toCss : Stroke -> Css.Px
toCss (Stroke value) =
    value

{-| 
-}
sm : Stroke
sm =
    Stroke <| Css.px 1


{-| 
-}
md : Stroke
md =
    Stroke <| Css.px 2


{-| 
-}
lg : Stroke
lg =
    Stroke <| Css.px 3

