// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playground": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/studio": {
    params: {};
  };
  "/resources/illustration-library": {
    params: {};
  };
  "/resources/illustration-library/all": {
    params: {};
  };
  "/resources/design-tokens": {
    params: {};
  };
  "/resources/icon-library": {
    params: {};
  };
  "/resources/icon-library/:category/:fileName": {
    params: {
      "category": string;
      "fileName": string;
    };
  };
  "/resources/icon-library/all-icons.zip": {
    params: {};
  };
  "/components/overview": {
    params: {};
  };
  "/components": {
    params: {};
  };
  "/:category/:slug": {
    params: {
      "category": string;
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/playground" | "/health" | "/studio" | "/resources/illustration-library" | "/resources/illustration-library/all" | "/resources/design-tokens" | "/resources/icon-library" | "/resources/icon-library/:category/:fileName" | "/resources/icon-library/all-icons.zip" | "/components/overview" | "/components" | "/:category/:slug";
  };
  "routes/playground/route.tsx": {
    id: "routes/playground";
    page: "/playground";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/health/route.tsx": {
    id: "routes/health";
    page: "/health";
  };
  "routes/studio/route.tsx": {
    id: "routes/studio";
    page: "/studio";
  };
  "routes/_base/route.tsx": {
    id: "routes/_base";
    page: "/resources/illustration-library" | "/resources/illustration-library/all" | "/resources/design-tokens" | "/resources/icon-library" | "/resources/icon-library/:category/:fileName" | "/resources/icon-library/all-icons.zip" | "/components/overview" | "/components" | "/:category/:slug";
  };
  "routes/_base.resources.illustration-library/route.tsx": {
    id: "routes/_base.resources.illustration-library";
    page: "/resources/illustration-library" | "/resources/illustration-library/all";
  };
  "routes/_base.resources.illustration-library.all/route.tsx": {
    id: "routes/_base.resources.illustration-library.all";
    page: "/resources/illustration-library/all";
  };
  "routes/_base.resources.design-tokens/route.tsx": {
    id: "routes/_base.resources.design-tokens";
    page: "/resources/design-tokens";
  };
  "routes/_base.resources.icon-library/route.tsx": {
    id: "routes/_base.resources.icon-library";
    page: "/resources/icon-library" | "/resources/icon-library/:category/:fileName" | "/resources/icon-library/all-icons.zip";
  };
  "routes/_base.resources.icon-library.$category.$fileName/route.tsx": {
    id: "routes/_base.resources.icon-library.$category.$fileName";
    page: "/resources/icon-library/:category/:fileName";
  };
  "routes/_base.resources.icon-library.all-icons[.zip]/route.tsx": {
    id: "routes/_base.resources.icon-library.all-icons[.zip]";
    page: "/resources/icon-library/all-icons.zip";
  };
  "routes/_base.components.overview/route.tsx": {
    id: "routes/_base.components.overview";
    page: "/components/overview";
  };
  "routes/_base.components._index/route.tsx": {
    id: "routes/_base.components._index";
    page: "/components";
  };
  "routes/_base.$category.$slug/route.tsx": {
    id: "routes/_base.$category.$slug";
    page: "/:category/:slug";
  };
};