/* eslint-disable @typescript-eslint/no-empty-object-type */
// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/playground": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/studio": {
    params: {};
  };
  "/:category/:slug": {
    params: {
      category: string;
      slug: string;
    };
  };
  "/:slug": {
    params: {
      slug: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page:
      | "/"
      | "/playground"
      | "/health"
      | "/studio"
      | "/:category/:slug"
      | "/:slug";
  };
  "routes/playground/route.tsx": {
    id: "routes/playground";
    page: "/playground";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/health/route.tsx": {
    id: "routes/health";
    page: "/health";
  };
  "routes/studio/route.tsx": {
    id: "routes/studio";
    page: "/studio";
  };
  "routes/_base/route.tsx": {
    id: "routes/_base";
    page: "/:category/:slug" | "/:slug";
  };
  "routes/_base.$category.$slug/route.tsx": {
    id: "routes/_base.$category.$slug";
    page: "/:category/:slug";
  };
  "routes/_base.$slug/route.tsx": {
    id: "routes/_base.$slug";
    page: "/:slug";
  };
};
