version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/studio"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-design-tokens"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-icon"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-icon-react"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-icon-react-native"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-loader"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/spor-react"
    schedule:
      interval: "weekly"
