version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 10
    reviewers:
      - nsbno/team-kanaler
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Oslo
    open-pull-requests-limit: 5
    reviewers:
      - nsbno/team-kanaler
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: chore
      include: scope
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
