// Generated by React Router

import type { GetAnnotations, GetInfo } from "react-router/internal";

type Module = typeof import("../root.js");

type Info = GetInfo<{
  file: "root.tsx";
  module: Module;
}>;

type Matches = [
  {
    id: "root";
    module: typeof import("../root.js");
  },
];

type Annotations = GetAnnotations<Info & { module: Module; matches: Matches }>;

// links
export type RouteLinkDescriptors = Annotations["LinkDescriptors"];
export type RouteLinksFunction = Annotations["LinksFunction"];

// meta
export type RouteMetaArgs = Annotations["MetaArgs"];
export type RouteMetaDescriptors = Annotations["MetaDescriptors"];
export type RouteMetaFunction = Annotations["MetaFunction"];

// headers
export type RouteHeadersArgs = Annotations["HeadersArgs"];
export type RouteHeadersFunction = Annotations["HeadersFunction"];

// unstable_middleware
export type RouteUnstable_MiddlewareFunction =
  Annotations["unstable_MiddlewareFunction"];

// unstable_clientMiddleware
export type RouteUnstable_ClientMiddlewareFunction =
  Annotations["unstable_ClientMiddlewareFunction"];

// loader
export type RouteLoaderArgs = Annotations["LoaderArgs"];

// clientLoader
export type RouteClientLoaderArgs = Annotations["ClientLoaderArgs"];

// action
export type RouteActionArgs = Annotations["ActionArgs"];

// clientAction
export type RouteClientActionArgs = Annotations["ClientActionArgs"];

// HydrateFallback
export type RouteHydrateFallbackProps = Annotations["HydrateFallbackProps"];

// Component
export type RouteComponentProps = Annotations["ComponentProps"];

// ErrorBoundary
export type RouteErrorBoundaryProps = Annotations["ErrorBoundaryProps"];
