module Spor.Token.Color.Alias exposing (Alias, toCss, lightGrey, platinum, silver, steel, osloGrey, dimGrey, darkGrey, seaFoam, opal, river, celadon, pine, darkTeal, night, mint, seaMist, coralGreen, blueGreen, azure, greenHaze, primaryGreen, icyBlue, lightBlue, cloudy, sky, glacier, ocean, darkBlue, cornsilk, blonde, primrose, sunshine, banana, burntYellow, golden, bisque, champagne, rajah, saffron, pumpkin, chocolate, wood, lightRed, brightRed, white, black)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Alias, toCss, lightGrey, platinum, silver, steel, osloGrey, dimGrey, darkGrey, seaFoam, opal, river, celadon, pine, darkTeal, night, mint, seaMist, coralGreen, blueGreen, azure, greenHaze, primaryGreen, icyBlue, lightBlue, cloudy, sky, glacier, ocean, darkBlue, cornsilk, blonde, primrose, sunshine, banana, burntYellow, golden, bisque, champagne, rajah, saffron, pumpkin, chocolate, wood, lightRed, brightRed, white, black
-}

import Css

{-| An opaque type representing a Alias value.
-}
type Alias =
    Alias Css.Color

{-| Convert Alias into Css.Color.
-}
toCss : Alias -> Css.Color
toCss (Alias value) =
    value

{-| 
-}
lightGrey : Alias
lightGrey =
    Alias <| Css.hex "#f5f5f5"


{-| 
-}
platinum : Alias
platinum =
    Alias <| Css.hex "#ebebec"


{-| 
-}
silver : Alias
silver =
    Alias <| Css.hex "#d7d8d9"


{-| 
-}
steel : Alias
steel =
    Alias <| Css.hex "#afb2b3"


{-| 
-}
osloGrey : Alias
osloGrey =
    Alias <| Css.hex "#888b8e"


{-| 
-}
dimGrey : Alias
dimGrey =
    Alias <| Css.hex "#606568"


{-| 
-}
darkGrey : Alias
darkGrey =
    Alias <| Css.hex "#2b2b2c"


{-| 
-}
seaFoam : Alias
seaFoam =
    Alias <| Css.hex "#cce1df"


{-| 
-}
opal : Alias
opal =
    Alias <| Css.hex "#99c3bf"


{-| 
-}
river : Alias
river =
    Alias <| Css.hex "#66a49e"


{-| 
-}
celadon : Alias
celadon =
    Alias <| Css.hex "#33867e"


{-| 
-}
pine : Alias
pine =
    Alias <| Css.hex "#00685e"


{-| 
-}
darkTeal : Alias
darkTeal =
    Alias <| Css.hex "#00453e"


{-| 
-}
night : Alias
night =
    Alias <| Css.hex "#012622"


{-| 
-}
mint : Alias
mint =
    Alias <| Css.hex "#e5f4f1"


{-| 
-}
seaMist : Alias
seaMist =
    Alias <| Css.hex "#cceae4"


{-| 
-}
coralGreen : Alias
coralGreen =
    Alias <| Css.hex "#b2dfd7"


{-| 
-}
blueGreen : Alias
blueGreen =
    Alias <| Css.hex "#84cfc2"


{-| 
-}
azure : Alias
azure =
    Alias <| Css.hex "#38b49e"


{-| 
-}
greenHaze : Alias
greenHaze =
    Alias <| Css.hex "#00957a"


{-| 
-}
primaryGreen : Alias
primaryGreen =
    Alias <| Css.hex "#037d67"


{-| 
-}
icyBlue : Alias
icyBlue =
    Alias <| Css.hex "#edf1f7"


{-| 
-}
lightBlue : Alias
lightBlue =
    Alias <| Css.hex "#dce4ef"


{-| 
-}
cloudy : Alias
cloudy =
    Alias <| Css.hex "#b9c9de"


{-| 
-}
sky : Alias
sky =
    Alias <| Css.hex "#a7bcd6"


{-| 
-}
glacier : Alias
glacier =
    Alias <| Css.hex "#688cba"


{-| 
-}
ocean : Alias
ocean =
    Alias <| Css.hex "#325d93"


{-| 
-}
darkBlue : Alias
darkBlue =
    Alias <| Css.hex "#003a70"


{-| 
-}
cornsilk : Alias
cornsilk =
    Alias <| Css.hex "#fef9dd"


{-| 
-}
blonde : Alias
blonde =
    Alias <| Css.hex "#fdf3ba"


{-| 
-}
primrose : Alias
primrose =
    Alias <| Css.hex "#fcec98"


{-| 
-}
sunshine : Alias
sunshine =
    Alias <| Css.hex "#fbe675"


{-| 
-}
banana : Alias
banana =
    Alias <| Css.hex "#fae053"


{-| 
-}
burntYellow : Alias
burntYellow =
    Alias <| Css.hex "#f1c400"


{-| 
-}
golden : Alias
golden =
    Alias <| Css.hex "#e5a80c"


{-| 
-}
bisque : Alias
bisque =
    Alias <| Css.hex "#ffe6cc"


{-| 
-}
champagne : Alias
champagne =
    Alias <| Css.hex "#ffcd99"


{-| 
-}
rajah : Alias
rajah =
    Alias <| Css.hex "#ffb466"


{-| 
-}
saffron : Alias
saffron =
    Alias <| Css.hex "#ff9b33"


{-| 
-}
pumpkin : Alias
pumpkin =
    Alias <| Css.hex "#ff8200"


{-| 
-}
chocolate : Alias
chocolate =
    Alias <| Css.hex "#cf6c05"


{-| 
-}
wood : Alias
wood =
    Alias <| Css.hex "#a75a0a"


{-| 
-}
lightRed : Alias
lightRed =
    Alias <| Css.hex "#fbcccc"


{-| 
-}
brightRed : Alias
brightRed =
    Alias <| Css.hex "#ed0000"


{-| 
-}
white : Alias
white =
    Alias <| Css.hex "#ffffff"


{-| 
-}
black : Alias
black =
    Alias <| Css.hex "#000000"

