module Spor.Token.Color.Background exposing (Background, toCss, white, lightGrey)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Background, toCss, white, lightGrey
-}

import Css

{-| An opaque type representing a Background value.
-}
type Background =
    Background Css.Color

{-| Convert Background into Css.Color.
-}
toCss : Background -> Css.Color
toCss (Background value) =
    value

{-| 
-}
white : Background
white =
    Background <| Css.hex "#ffffff"


{-| 
-}
lightGrey : Background
lightGrey =
    Background <| Css.hex "#f5f5f5"

