module Spor.Token.Color.Detail exposing (Detail, toCss, darkBlue, ocean, golden, burntYellow, wood, chocolate, pumpkin)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Detail, toCss, darkBlue, ocean, golden, burntYellow, wood, chocolate, pumpkin
-}

import Css

{-| An opaque type representing a Detail value.
-}
type Detail =
    Detail Css.Color

{-| Convert Detail into Css.Color.
-}
toCss : Detail -> Css.Color
toCss (Detail value) =
    value

{-| 
-}
darkBlue : Detail
darkBlue =
    Detail <| Css.hex "#003a70"


{-| 
-}
ocean : Detail
ocean =
    Detail <| Css.hex "#325d93"


{-| 
-}
golden : Detail
golden =
    Detail <| Css.hex "#e5a80c"


{-| 
-}
burntYellow : Detail
burntYellow =
    Detail <| Css.hex "#f1c400"


{-| 
-}
wood : Detail
wood =
    Detail <| Css.hex "#a75a0a"


{-| 
-}
chocolate : Detail
chocolate =
    Detail <| Css.hex "#cf6c05"


{-| 
-}
pumpkin : Detail
pumpkin =
    Detail <| Css.hex "#ff8200"

