module Spor.Token.Color.Outline exposing (Outline, toCss, osloGrey, greenHaze, darkGrey, black)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Outline, toCss, osloGrey, greenHaze, darkGrey, black
-}

import Css

{-| An opaque type representing a Outline value.
-}
type Outline =
    Outline Css.Color

{-| Convert Outline into Css.Color.
-}
toCss : Outline -> Css.Color
toCss (Outline value) =
    value

{-| Used on tertiary buttons, cards and separators, among others
-}
osloGrey : Outline
osloGrey =
    Outline <| Css.hex "#888b8e"


{-| Used for focus state outlines
-}
greenHaze : Outline
greenHaze =
    Outline <| Css.hex "#00957a"


{-| 
-}
darkGrey : Outline
darkGrey =
    Outline <| Css.hex "#2b2b2c"


{-| 
-}
black : Outline
black =
    Outline <| Css.hex "#000000"

