module Spor.Token.Color.Product exposing (Product, toCss, ocean, wood)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Product, toCss, ocean, wood
-}

import Css

{-| An opaque type representing a Product value.
-}
type Product =
    Product Css.Color

{-| Convert Product into Css.Color.
-}
toCss : Product -> Css.Color
toCss (Product value) =
    value

{-| Used for the Smartpris product
-}
ocean : Product
ocean =
    Product <| Css.hex "#325d93"


{-| Used for the Flexbillett product
-}
wood : Product
wood =
    Product <| Css.hex "#a75a0a"

