module Spor.Token.Color.Text exposing (Text, toCss, darkGrey, white, darkTeal)

{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.

@docs Text, toCss, darkGrey, white, darkTeal
-}

import Css

{-| An opaque type representing a Text value.
-}
type Text =
    Text Css.Color

{-| Convert Text into Css.Color.
-}
toCss : Text -> Css.Color
toCss (Text value) =
    value

{-| Used for typography and icons on light backgrounds
-}
darkGrey : Text
darkGrey =
    Text <| Css.hex "#2b2b2c"


{-| Used for typography and icons on dark backgrounds
-}
white : Text
white =
    Text <| Css.hex "#ffffff"


{-| Used primarily for links
-}
darkTeal : Text
darkTeal =
    Text <| Css.hex "#00453e"

