import { Format, Named, File, TransformedToken } from 'style-dictionary';
import { unSnake } from '../../transforms/elm/name';

const moduleNamePrefix = 'Spor.Token';
const defaultIndentation = '    ';

export const elmFormatter: Named<Format> = {
    name: 'elm/module',
    formatter: function({ dictionary, file }) {
        const moduleName = generateModuleName(file.options);
        const moduleType = generateModuleType(file.options);

        const complexProps = buildComplexProps(dictionary.allProperties); 

        const exposing = moduleType.exposings()
            .concat(Array.from(complexProps.keys()))
            .join(', ');

        const definitions = moduleType.definitions().concat(
            Array.from(complexProps.entries())
                .map(([name, prop]) => moduleType.generateElmConstant(name, prop))
                .flat()
        );

        return [
            `module ${moduleName} exposing (${exposing})`,
            '',
            `{-| This module was automaticly generated by the [spor-design-tokens](https://github.com/nsbno/spor) project.`,
            '',
            `@docs ${exposing}`,
            '-}',
            '',
        ].concat(...moduleType.imports(), '')
         .concat(...definitions)
         .join('\n');
    }
};

function buildComplexProps(properties: Array<TransformedToken>): Map<string, any> {
    const result = new Map();

    for (let prop of properties) {
        if (!prop.attributes) {
            continue;
        }
        
        const item = unSnake(prop.attributes.item || '');
        
        if (prop.attributes.subitem) {
            const current = result.get(item) || {};
            
            current.value =  (current.value ? current.value + ' ' : '') + prop.value;
            current.comment = current.comment || prop.comment;
            current[prop.attributes.subitem] = prop.value;
            
            result.set(item, current);
        } else {
            result.set(item, { 
                value: prop.value,
                comment: prop.comment
            });
        }
    }
    
    return result;
}

function generateModuleName(options: any): string {
    return `${moduleNamePrefix}.${options.category}.${options.type}`;
}


type ModuleWrappedType = {
    name: string;
    construct: (input: string) => string;
};

class ModuleType {
    name: string;
    wrappedType: ModuleWrappedType;

    constructor(name: string, wrappedType: ModuleWrappedType) {
        this.name = name;
        this.wrappedType = wrappedType;
    }

    imports(): Array<string> {
        const wrapped = this.wrappedType.name;

        if (['Int', 'Float', 'String'].includes(wrapped)) {
            return [];
        } 

        return [ 'import Css' ];
    }

    exposings(): Array<string> {
        return [
            this.name,
            this.unwrapperName()
        ];
    }

    unwrapperName(): string {
        const wrapped = this.wrappedType.name;

        let unwrapper;
        if (['Int', 'Float', 'String'].includes(wrapped)) {
            unwrapper = `to${wrapped}`;
        } else {
            unwrapper = 'toCss';
        }

        return unwrapper;
    }

    definitions(): Array<string> {
        const unwrapperName = this.unwrapperName();

        return [
            `{-| An opaque type representing a ${this.name} value.`,
            '-}',
            `type ${this.name} =`,
            `${defaultIndentation}${this.name} ${this.wrappedType.name}`,
            '',
            `{-| Convert ${this.name} into ${this.wrappedType.name}.`,
            '-}',
            `${unwrapperName} : ${this.name} -> ${this.wrappedType.name}`,
            `${unwrapperName} (${this.name} value) =`,
            `${defaultIndentation}value`,
            ''
        ];
    }

    generateElmConstant(name: string, prop: any): Array<string> {
        return [
            `{-| ${prop.comment || ''}`,
            '-}',
            `${name} : ${this.name}`,
            `${name} =`,
                `${defaultIndentation}${this.name} <| ${this.wrappedType.construct(prop)}`,
            '',
            ''
        ];
    }
};


const intTypeConstruction: ModuleWrappedType = {
    name: 'Int',
    construct(prop: any): string {
        return prop.value;
    }
};

const floatTypeConstruction: ModuleWrappedType = {
    name: 'Float',
    construct(prop: any): string {
        return prop.value;
    }
};

const stringTypeConstruction: ModuleWrappedType = {
    name: 'String',
    construct(prop: any): string {
        return asString(prop.value);
    }
};

const colorTypeConstruction: ModuleWrappedType = {
    name: 'Css.Color',
    construct: colorConstructor
};

function colorConstructor(prop: any): string {
    const input: string = prop.value;
    
    if (input.startsWith('#')) {
        return `Css.hex ${asString(input)}`
    } else if (input.startsWith('rgba')) {
        // remove the first five characters 'rgba(' and the last character ')
        const args = input.slice(5, -1).split(',').map((s: string) => s.trim());
        return `Css.rgba ${args[0]} ${args[1]} ${args[2]} ${args[3]}`
    }

    throw new Error(`Don\'t know how to handle this color value: ${input}`);
}

const pxTypeConstruction: ModuleWrappedType = {
    name: 'Css.Px',
    construct: sizeConstructor
};

function sizeConstructor(prop: any): string {
    const input: string = prop.value;
    
    if (input === '0') {
        return 'Css.zero';
    } else if (input.endsWith('px')) {
        const rawValue = input.replace(/px$/, '');
        return `Css.px ${rawValue}`;
    }

    throw new Error(`Don\'t know how to handle this size value: ${input}`);
}

const shadowTypeConstruction: ModuleWrappedType = {
    name: 'Css.Style',

    construct(prop: any): string {
        const rgbaRegex = /rgba\(.*\)/;

        const input: string = prop.value;
        const color = colorConstructor({ value: (input.match(rgbaRegex) || [])[0] || ''});
        const sizes = input
            .replace(rgbaRegex, '')
            .trim()
            .split(/\s/)
            .map(arg => sizeConstructor({ value: arg }));

        const args = sizes.concat(color).map(arg => `(${arg})`);

        switch(args.length) {
            case 4: return `Css.boxShadow4 ${args.join(' ')}`;
            case 5: return `Css.boxShadow5 ${args.join(' ')}`;
            default:
                throw new Error(`Don\'t know how to handle this box-shadow value: ${input}`);
        }
    }
};

const moduleTypeInnerType: Map<string, ModuleWrappedType> = new Map([
    ['Alias', colorTypeConstruction],
    ['Background', colorTypeConstruction],
    ['Detail', colorTypeConstruction],
    ['Error', colorTypeConstruction],
    ['Linjetag', colorTypeConstruction],
    ['Main', colorTypeConstruction],
    ['Outline', colorTypeConstruction],
    ['Palette', colorTypeConstruction],
    ['Product', colorTypeConstruction],
    ['Text', colorTypeConstruction],
    ['Shadow', shadowTypeConstruction],
    ['ZIndex', intTypeConstruction],
    ['BorderRadius', pxTypeConstruction],
    ['Breakpoint', pxTypeConstruction],
    ['LineHeight', floatTypeConstruction],
    ['Spacing', pxTypeConstruction],
    ['Stroke', pxTypeConstruction]
]);

function generateModuleType(options: any): ModuleType {
    const wrappedType = moduleTypeInnerType.get(options.type) || stringTypeConstruction;
    return new ModuleType(options.type, wrappedType);
}

function asString(input: any): string {
    return `\"${input.toString().replaceAll('"', '\\"')}\"`;
}
