import "@testing-library/jest-dom";

// jsdom doesn't implement window.matchMedia, which is required by next-themes.
Object.defineProperty(globalThis, "matchMedia", {
  writable: true,
  value: (query: string) => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: () => {},
    removeListener: () => {},
    addEventListener: () => {},
    removeEventListener: () => {},
    dispatchEvent: () => false,
  }),
});

// jsdom doesn't implement HTMLCanvasElement.getContext(), which causes lottie-web to crash.
// Return a no-op mock context so canvas-based animations are silently skipped in tests.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(HTMLCanvasElement.prototype as any).getContext = () =>
  ({
    fillStyle: "",
    strokeStyle: "",
    lineWidth: 0,
    lineCap: "",
    lineJoin: "",
    globalAlpha: 1,
    globalCompositeOperation: "",
    shadowBlur: 0,
    shadowColor: "",
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    font: "",
    textAlign: "",
    textBaseline: "",
    canvas: document.createElement("canvas"),
    save: () => {},
    restore: () => {},
    scale: () => {},
    rotate: () => {},
    translate: () => {},
    transform: () => {},
    setTransform: () => {},
    resetTransform: () => {},
    clearRect: () => {},
    fillRect: () => {},
    strokeRect: () => {},
    beginPath: () => {},
    closePath: () => {},
    moveTo: () => {},
    lineTo: () => {},
    bezierCurveTo: () => {},
    quadraticCurveTo: () => {},
    arc: () => {},
    arcTo: () => {},
    ellipse: () => {},
    rect: () => {},
    fill: () => {},
    stroke: () => {},
    clip: () => {},
    drawImage: () => {},
    createLinearGradient: () => ({ addColorStop: () => {} }),
    createRadialGradient: () => ({ addColorStop: () => {} }),
    createPattern: () => null,
    measureText: () => ({ width: 0 }),
    fillText: () => {},
    strokeText: () => {},
    getImageData: () => ({
      data: new Uint8ClampedArray(0),
      width: 0,
      height: 0,
    }),
    putImageData: () => {},
    createImageData: () => ({
      data: new Uint8ClampedArray(0),
      width: 0,
      height: 0,
    }),
    setLineDash: () => {},
    getLineDash: () => [],
    isPointInPath: () => false,
    isPointInStroke: () => false,
  }) as unknown as CanvasRenderingContext2D;
