export const contentLoaderPrideData = {
  nm: "_Loading_square",
  h: 430,
  w: 430,
  meta: { g: "LottieFiles AE 1.1.0" },
  layers: [
    {
      ty: 4,
      nm: "Layer 3 Outlines",
      sr: 1,
      st: 165.165,
      op: 222.723,
      ip: 165.165,
      hasMask: false,
      ao: 0,
      ks: {
        a: { a: 0, k: [49.648, 52.604, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
        sk: { a: 0, k: 0 },
        p: { a: 0, k: [224.279, 227.214, 0], ix: 2 },
        r: { a: 0, k: 0, ix: 10 },
        sa: { a: 0, k: 0 },
        o: { a: 0, k: 100, ix: 11 },
      },
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          nm: "Group 1",
          ix: 1,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: false,
                  i: [
                    [0, 0],
                    [-9.548, -8.116],
                    [12.213, 7.96],
                    [-12.659, 7.277],
                    [12.618, 4.454],
                    [2.352, -3.056],
                    [0.498, -2.699],
                    [9.977, 2.146],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [9.549, 8.115],
                    [-7.226, -4.71],
                    [16.161, -9.29],
                    [-10.839, -3.826],
                    [-1.674, 2.175],
                    [-0.787, 4.264],
                    [-9.596, -2.065],
                    [0, 0],
                  ],
                  v: [
                    [-19.358, 5.322],
                    [22.599, 11.997],
                    [9.696, 27.143],
                    [13.051, -1.568],
                    [13.922, -31.277],
                    [-5.688, -26.311],
                    [-8.89, -18.844],
                    [-22.552, -7.117],
                    [-32.1, -20.439],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "st",
              nm: "Stroke 1",
              lc: 2,
              lj: 2,
              ml: 1,
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              c: { a: 0, k: [0.228, 0.024, 0.573], ix: 3 },
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 3,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.4, y: 0 },
                    i: { x: 0.15, y: 1 },
                    s: [0],
                    t: 165.999,
                  },
                  { s: [100], t: 191.859 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.85, y: 0 },
                    i: { x: 0.61, y: 1 },
                    s: [0],
                    t: 196.029,
                  },
                  { s: [100], t: 221.055 },
                ],
                ix: 1,
              },
              m: 1,
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [49.648, 52.604], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Group 2",
          ix: 2,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: true,
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "fl",
              nm: "Fill 1",
              c: { a: 0, k: [0.51, 0.094, 0.537], ix: 4 },
              r: 1,
              o: { a: 0, k: 100, ix: 5 },
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0, 0],
                    t: 165.999,
                  },
                  { s: [100, 100], t: 170.17 },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [17.548, 19.917], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
      ],
      ind: 1,
    },
    {
      ty: 4,
      nm: "Layer 6 Outlines",
      sr: 1,
      st: 114.281,
      op: 200.2,
      ip: 114.281,
      hasMask: false,
      ao: 0,
      ks: {
        a: { a: 0, k: [48.039, 44.207, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
        sk: { a: 0, k: 0 },
        p: { a: 0, k: [229.967, 255.217, 0], ix: 2 },
        r: { a: 0, k: 0, ix: 10 },
        sa: { a: 0, k: 0 },
        o: { a: 0, k: 100, ix: 11 },
      },
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          nm: "Group 1",
          ix: 1,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: false,
                  i: [
                    [0, 0],
                    [-5.419, -6],
                    [12.941, -9.498],
                    [-11.033, 22.987],
                    [9.29, -3.097],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [6.622, 7.33],
                    [-12.942, 9.497],
                    [11.032, -22.988],
                    [-9.29, 3.096],
                    [0, 0],
                  ],
                  v: [
                    [11.43, -26.475],
                    [14.719, -10.507],
                    [17.598, 16.978],
                    [-7.732, 0.288],
                    [-20.312, -22.893],
                    [-30.538, -12.025],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "st",
              nm: "Stroke 1",
              lc: 2,
              lj: 2,
              ml: 1,
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              c: { a: 0, k: [0.243, 0.549, 0.149], ix: 3 },
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 3,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.4, y: 0 },
                    i: { x: 0.15, y: 1 },
                    s: [0],
                    t: 115.115,
                  },
                  { s: [100], t: 136.803 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.85, y: 0 },
                    i: { x: 0.61, y: 1 },
                    s: [0],
                    t: 140.974,
                  },
                  { s: [100], t: 161.829 },
                ],
                ix: 1,
              },
              m: 1,
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [48.039, 44.439], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Group 2",
          ix: 2,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: true,
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "fl",
              nm: "Fill 1",
              c: { a: 0, k: [0.337, 0.741, 0.749], ix: 4 },
              r: 1,
              o: { a: 0, k: 100, ix: 5 },
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0, 0],
                    t: 115.115,
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [100, 100],
                    t: 120.12,
                  },
                  {
                    o: { x: 0.61, y: 0 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100],
                    t: 196.029,
                  },
                  { s: [0, 0], t: 200.2 },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [14.801, 44.726], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
      ],
      ind: 2,
    },
    {
      ty: 4,
      nm: "Layer 4 Outlines",
      sr: 1,
      st: 55.055,
      op: 145.145,
      ip: 55.055,
      hasMask: false,
      ao: 0,
      ks: {
        a: { a: 0, k: [47.397, 48.847, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
        sk: { a: 0, k: 0 },
        p: { a: 0, k: [197.76, 233.027, 0], ix: 2 },
        r: { a: 0, k: 0, ix: 10 },
        sa: { a: 0, k: 0 },
        o: { a: 0, k: 100, ix: 11 },
      },
      ef: [
        {
          ty: 5,
          nm: "Group 3 - Contents - Overshoot",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 3 - Contents - Bounce",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 3 - Contents - Friction",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          nm: "Group 1",
          ix: 1,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: false,
                  i: [
                    [0, 0],
                    [20.129, -10.827],
                    [-26.542, -1.082],
                    [11.227, -3.364],
                    [3.097, 10.452],
                    [-7.882, 2.597],
                  ],
                  o: [
                    [0, 0],
                    [-20.355, 9.691],
                    [33.252, 1.354],
                    [-7.446, 2.231],
                    [-4.178, -14.1],
                    [0, 0],
                  ],
                  v: [
                    [22.774, 17.818],
                    [-3.742, 21.657],
                    [-3.355, 2.883],
                    [9.226, -17.247],
                    [-18.452, -17.247],
                    [7.774, -30.014],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "st",
              nm: "Stroke 1",
              lc: 2,
              lj: 2,
              ml: 1,
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              c: { a: 0, k: [0.941, 0.58, 0.212], ix: 3 },
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 3,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.4, y: 0 },
                    i: { x: 0.15, y: 1 },
                    s: [0],
                    t: 55.889,
                  },
                  { s: [100], t: 81.748 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.85, y: 0 },
                    i: { x: 0.61, y: 1 },
                    s: [0],
                    t: 85.919,
                  },
                  { s: [100], t: 110.945 },
                ],
                ix: 1,
              },
              m: 1,
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [47.397, 48.847], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Group 3",
          ix: 3,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: true,
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "fl",
              nm: "Fill 1",
              c: { a: 0, k: [1, 1, 0.329], ix: 4 },
              r: 1,
              o: { a: 0, k: 100, ix: 5 },
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0, 0],
                    t: 55.889,
                  },
                  {
                    o: { x: 0.167, y: 0 },
                    i: { x: 0.833, y: 1 },
                    s: [100, 100],
                    t: 59.226,
                  },
                  {
                    o: { x: 0.61, y: 0 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100],
                    t: 140.974,
                  },
                  { s: [0, 0], t: 145.145 },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [67.183, 14.998], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
      ],
      ind: 3,
    },
    {
      ty: 4,
      nm: "Layer 5 Outlines",
      sr: 1,
      st: 0,
      op: 90.09,
      ip: 0,
      hasMask: false,
      ao: 0,
      ks: {
        a: { a: 0, k: [42.323, 44.529, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
        sk: { a: 0, k: 0 },
        p: { a: 0, k: [242.84, 220.002, 0], ix: 2 },
        r: { a: 0, k: 0, ix: 10 },
        sa: { a: 0, k: 0 },
        o: { a: 0, k: 100, ix: 11 },
      },
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          nm: "Group 1",
          ix: 1,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: false,
                  i: [
                    [0, 0],
                    [3.144, -9.317],
                    [-11.522, 11.368],
                    [11.612, -5.038],
                    [2.75, -9.989],
                    [-8.867, 1.58],
                    [-7.065, -5.935],
                  ],
                  o: [
                    [0, 0],
                    [-6.194, 18.348],
                    [8.806, -7.742],
                    [-7.152, 3.102],
                    [-2.283, 8.293],
                    [9.735, -1.736],
                    [0, 0],
                  ],
                  v: [
                    [-23.693, -27.029],
                    [-18.628, -14.835],
                    [16.016, 0.068],
                    [4.984, -13.862],
                    [-21.725, 12.017],
                    [-8.564, 25.449],
                    [14.178, 20.1],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "st",
              nm: "Stroke 1",
              lc: 2,
              lj: 2,
              ml: 1,
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              c: { a: 0, k: [0.929, 0.435, 0.6], ix: 3 },
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 3,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.4, y: 0 },
                    i: { x: 0.15, y: 1 },
                    s: [0],
                    t: 5.005,
                  },
                  { s: [100], t: 26.693 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.85, y: 0 },
                    i: { x: 0.61, y: 1 },
                    s: [0],
                    t: 30.864,
                  },
                  { s: [100], t: 51.719 },
                ],
                ix: 1,
              },
              m: 1,
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [42.322, 44.529], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Group 2",
          ix: 2,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: true,
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.67, 0],
                    [0.001, -5.669],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "fl",
              nm: "Fill 1",
              c: { a: 0, k: [0.918, 0.2, 0.137], ix: 4 },
              r: 1,
              o: { a: 0, k: 100, ix: 5 },
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [0, 0],
                    t: 5.005,
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100],
                    t: 9.176,
                  },
                  {
                    o: { x: 0.167, y: 0.167 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100],
                    t: 85.919,
                  },
                  { s: [0, 0], t: 90.09 },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [66.038, 72.812], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
        {
          ty: "gr",
          nm: "Group 3",
          ix: 3,
          cix: 2,
          it: [
            {
              ty: "sh",
              nm: "Path 1",
              ix: 1,
              d: 1,
              ks: {
                a: 0,
                k: {
                  c: true,
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                },
                ix: 2,
              },
            },
            {
              ty: "fl",
              nm: "Fill 1",
              c: { a: 0, k: [0.51, 0.094, 0.537], ix: 4 },
              r: 1,
              o: { a: 0, k: 100, ix: 5 },
            },
            {
              ty: "tr",
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.61, y: 0 },
                    i: { x: 0.833, y: 0.833 },
                    s: [100, 100],
                    t: 35.869,
                  },
                  { s: [0, 0], t: 40.04 },
                ],
                ix: 3,
              },
              sk: { a: 0, k: 0, ix: 4 },
              p: { a: 0, k: [6.51, 13.285], ix: 2 },
              r: { a: 0, k: 0, ix: 6 },
              sa: { a: 0, k: 0, ix: 5 },
              o: { a: 0, k: 100, ix: 7 },
            },
          ],
        },
      ],
      ind: 4,
    },
  ],
  v: "4.8.0",
  fr: 25,
  op: 222,
  ip: 0,
  assets: [],
};
