export const contentLoaderData = {
  v: "4.8.0",
  meta: { g: "LottieFiles AE 1.1.0", a: "", k: "", d: "", tc: "" },
  fr: 25,
  ip: 0,
  op: 222,
  w: 430,
  h: 430,
  nm: "_Loading_square",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Layer 3 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [224.279, 227.214, 0], ix: 2 },
        a: { a: 0, k: [49.648, 52.604, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [-9.548, -8.116],
                    [12.213, 7.96],
                    [-12.659, 7.277],
                    [12.618, 4.454],
                    [2.352, -3.056],
                    [0.498, -2.699],
                    [9.977, 2.146],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [9.549, 8.115],
                    [-7.226, -4.71],
                    [16.161, -9.29],
                    [-10.839, -3.826],
                    [-1.674, 2.175],
                    [-0.787, 4.264],
                    [-9.596, -2.065],
                    [0, 0],
                  ],
                  v: [
                    [-19.358, 5.322],
                    [22.599, 11.997],
                    [9.696, 27.143],
                    [13.051, -1.568],
                    [13.922, -31.277],
                    [-5.688, -26.311],
                    [-8.89, -18.844],
                    [-22.552, -7.117],
                    [-32.1, -20.439],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.984313785329, 0.901960844152, 0.458823559331, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 196.029,
                    s: [0],
                  },
                  { t: 221.054813602665, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.4], y: [0] },
                    t: 165.999,
                    s: [0],
                  },
                  { t: 191.858524540165, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [49.648, 52.604], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.517647058824, 0.811764765721, 0.760784373564, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [17.548, 19.917], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 165.999,
                    s: [0, 0],
                  },
                  { t: 170.170047977665, s: [100, 100] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 165.165165165165,
      op: 222.722722722723,
      st: 165.165165165165,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: "Layer 6 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [229.967, 255.217, 0], ix: 2 },
        a: { a: 0, k: [48.039, 44.207, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [-5.419, -6],
                    [12.941, -9.498],
                    [-11.033, 22.987],
                    [9.29, -3.097],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [6.622, 7.33],
                    [-12.942, 9.497],
                    [11.032, -22.988],
                    [-9.29, 3.096],
                    [0, 0],
                  ],
                  v: [
                    [11.43, -26.475],
                    [14.719, -10.507],
                    [17.598, 16.978],
                    [-7.732, 0.288],
                    [-20.312, -22.893],
                    [-30.538, -12.025],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.196078446332, 0.364705882353, 0.576470588235, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 140.974,
                    s: [0],
                  },
                  { t: 161.828799176781, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.4], y: [0] },
                    t: 115.115,
                    s: [0],
                  },
                  { t: 136.803408551781, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [48.039, 44.439], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: { a: 0, k: [1, 0.705882352941, 0.400000029919, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [14.801, 44.726], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 115.115,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 120.12,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 196.029,
                    s: [100, 100],
                  },
                  { t: 200.199892926781, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 114.280947614281,
      op: 200.2002002002,
      st: 114.280947614281,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 5,
      ty: 4,
      nm: "Layer 4 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [197.76, 233.027, 0], ix: 2 },
        a: { a: 0, k: [47.397, 48.847, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: "Group 3 - Contents - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 3 - Contents - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 3 - Contents - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [20.129, -10.827],
                    [-26.542, -1.082],
                    [11.227, -3.364],
                    [3.097, 10.452],
                    [-7.882, 2.597],
                  ],
                  o: [
                    [0, 0],
                    [-20.355, 9.691],
                    [33.252, 1.354],
                    [-7.446, 2.231],
                    [-4.178, -14.1],
                    [0, 0],
                  ],
                  v: [
                    [22.774, 17.818],
                    [-3.742, 21.657],
                    [-3.355, 2.883],
                    [9.226, -17.247],
                    [-18.452, -17.247],
                    [7.774, -30.014],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: { a: 0, k: [0, 0.58431372549, 0.478431402468, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 85.919,
                    s: [0],
                  },
                  { t: 110.944703492555, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.4], y: [0] },
                    t: 55.889,
                    s: [0],
                  },
                  { t: 81.748414430055, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [47.397, 48.847], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: { a: 0, k: [0.945098099054, 0.768627510819, 0, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [67.183, 14.998], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 55.889,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 59.226,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 140.974,
                    s: [100, 100],
                  },
                  { t: 145.144898805055, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 3,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 55.0550550550551,
      op: 145.145145145145,
      st: 55.0550550550551,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 7,
      ty: 4,
      nm: "Layer 5 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [242.84, 220.002, 0], ix: 2 },
        a: { a: 0, k: [42.323, 44.529, 0], ix: 1 },
        s: { a: 0, k: [500, 500, 100], ix: 6 },
      },
      ao: 0,
      ef: [
        {
          ty: 5,
          nm: "Group 2 - Contents - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 1,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 2,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Group 2 - Contents - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 3,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Overshoot",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 4,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Bounce",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 5,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 20,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
        {
          ty: 5,
          nm: "Scale - Transform - Friction",
          np: 3,
          mn: "ADBE Slider Control",
          ix: 6,
          en: 1,
          ef: [
            {
              ty: 0,
              nm: "Slider",
              mn: "ADBE Slider Control-0001",
              ix: 1,
              v: {
                a: 0,
                k: 60,
                ix: 1,
                x: "var $bm_rt;\n$bm_rt = clamp(value, 0, 100);",
              },
            },
          ],
        },
      ],
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [3.144, -9.317],
                    [-11.522, 11.368],
                    [11.612, -5.038],
                    [2.75, -9.989],
                    [-8.867, 1.58],
                    [-7.065, -5.935],
                  ],
                  o: [
                    [0, 0],
                    [-6.194, 18.348],
                    [8.806, -7.742],
                    [-7.152, 3.102],
                    [-2.283, 8.293],
                    [9.735, -1.736],
                    [0, 0],
                  ],
                  v: [
                    [-23.693, -27.029],
                    [-18.628, -14.835],
                    [16.016, 0.068],
                    [4.984, -13.862],
                    [-21.725, 12.017],
                    [-8.564, 25.449],
                    [14.178, 20.1],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: { a: 0, k: [1, 0.509803921569, 0, 1], ix: 3 },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 30.864,
                    s: [0],
                  },
                  { t: 51.71875, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.4], y: [0] },
                    t: 5.005,
                    s: [0],
                  },
                  { t: 26.693359375, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [42.322, 44.529], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.67, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: { a: 0, k: [0, 0.227450995352, 0.439215716194, 1], ix: 4 },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [66.038, 72.812], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 5.005,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 9.176,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 85.919,
                    s: [100, 100],
                  },
                  { t: 90.08984375, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = $bm_div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = $bm_div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = $bm_div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : $bm_sub(time, key(n).time), $bm_rt = 0 < n ? (v = velocityAtTime($bm_sub(key(n).time, $bm_div(thisComp.frameDuration, 10))), $bm_sum(value, $bm_div($bm_mul($bm_mul($bm_div(v, 100), amp), Math.sin($bm_mul($bm_mul($bm_mul(freq, t), 2), Math.PI))), Math.exp($bm_mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.517647058824, 0.811764765721, 0.760784373564, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [6.51, 13.285], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 35.869,
                    s: [100, 100],
                  },
                  { t: 40.0400390625, s: [0, 0] },
                ],
                ix: 3,
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 3,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 0,
      op: 90.0900900900901,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
