export const inlineLoaderDarkData = {
  v: "4.8.0",
  meta: { g: "LottieFiles AE 2.0.4", a: "", k: "", d: "", tc: "" },
  fr: 25,
  ip: 0,
  op: 214,
  w: 200,
  h: 112,
  nm: "_Loading_horizontal 2",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Layer 6 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [99.127, 61.768, 0], ix: 2 },
        a: { a: 0, k: [67.987, 38.897, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [4.31, 12.068],
                    [-8.516, -1.548],
                    [4.442, -4.813],
                    [2.281, 13.167],
                    [5.048, -2.277],
                  ],
                  o: [
                    [0, 0],
                    [-1.935, -5.419],
                    [8.516, 1.549],
                    [-2.077, 2.251],
                    [-2.122, -12.245],
                    [0, 0],
                  ],
                  v: [
                    [28.331, 8.518],
                    [-2.492, -1.623],
                    [8.085, -13.817],
                    [11.545, 2.365],
                    [-13.564, 3.449],
                    [-26.331, -7.357],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 187.195,
                    s: [0],
                  },
                  { t: 212.2197265625, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.16], y: [1] },
                    o: { x: [0.38], y: [0] },
                    t: 157.999,
                    s: [0],
                  },
                  { t: 183.0244140625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 9, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [67.081, 38.897], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [28.7, 34.3], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.818, 0.818] },
                    o: { x: [0.167, 0.167], y: [0.182, 0.182] },
                    t: 157.999,
                    s: [0, 0],
                  },
                  { t: 163, s: [110, 110] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 157.1650390625,
      op: 214,
      st: 157.1650390625,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: "Layer 3 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [98.324, 49.628, 0], ix: 2 },
        a: { a: 0, k: [68.326, 35.646, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [-7.572, -1.01],
                    [3.971, 8.237],
                    [2.906, -6.182],
                    [-14.709, 1.775],
                    [-12.934, 0.447],
                    [-2.214, -3.454],
                  ],
                  o: [
                    [0, 0],
                    [16.664, 2.223],
                    [-3.742, -7.761],
                    [-4.13, 8.787],
                    [18.568, -2.24],
                    [5.555, -0.192],
                    [5.885, 9.181],
                  ],
                  v: [
                    [-34.508, 3.523],
                    [-23.633, 11.714],
                    [-0.653, -8.009],
                    [-17.714, -6.975],
                    [3.891, 17.895],
                    [25.601, -7.996],
                    [35.37, 0.516],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.6], y: [1] },
                    o: { x: [0.81], y: [0] },
                    t: 128.804,
                    s: [0],
                  },
                  { t: 153.828125, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.14], y: [1] },
                    o: { x: [0.41], y: [0] },
                    t: 100.442,
                    s: [0],
                  },
                  { t: 125.466796875, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 9, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [67.258, 35.645], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0, 5.669],
                    [-5.67, 0],
                    [0, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [109.684, 49.055], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.834, 0.834] },
                    o: { x: [0.167, 0.167], y: [0.166, 0.166] },
                    t: 100.442,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 105,
                    s: [110, 110],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.835, 0.835] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 191,
                    s: [110, 110],
                  },
                  { t: 195.537109375, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 99.607421875,
      op: 195.537109375,
      st: 99.607421875,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: "Layer 5 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [100.609, 53.612, 0], ix: 2 },
        a: { a: 0, k: [67.97, 41.759, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [7.02, -14.552],
                    [-5.418, 9.846],
                    [10, 0],
                  ],
                  o: [
                    [0, 0],
                    [-10.681, 22.143],
                    [6.29, -11.429],
                    [-8.134, 0],
                  ],
                  v: [
                    [23.845, -3.468],
                    [1.377, 6.426],
                    [-19.219, 5.998],
                    [-28.179, -11.056],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.59], y: [1] },
                    o: { x: [0.59], y: [0] },
                    t: 72.08,
                    s: [0],
                  },
                  { t: 97.10546875, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.25], y: [0] },
                    t: 44.553,
                    s: [0],
                  },
                  { t: 68.7431640625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 9, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [68.97, 41.759], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [27.016, 29.646], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.838, 0.838] },
                    o: { x: [0.167, 0.167], y: [0.162, 0.162] },
                    t: 44.553,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 49,
                    s: [110, 110],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.848, 0.848] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 132.14,
                    s: [110, 110],
                  },
                  { t: 136.3115234375, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 43.71875,
      op: 136.310546875,
      st: 44.552734375,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 4,
      ty: 4,
      nm: "Layer 1 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [99.77, 57.554, 0], ix: 2 },
        a: { a: 0, k: [68.113, 36.77, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [-12.162, -15.329],
                    [-0.351, 7.877],
                    [-10.918, -0.012],
                    [-15.581, 9.368],
                  ],
                  o: [
                    [8.109, 10.221],
                    [0.389, -8.726],
                    [14.198, 0.016],
                    [0, 0],
                  ],
                  v: [
                    [-29.463, 7.355],
                    [-12.149, 5.074],
                    [1.419, -13.754],
                    [27.738, 4.935],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 9, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.59], y: [1] },
                    o: { x: [0.78], y: [0] },
                    t: 23,
                    s: [0],
                  },
                  { t: 41, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.22], y: [1] },
                    o: { x: [0.6], y: [0] },
                    t: 2.503,
                    s: [0],
                  },
                  { t: 18.8291015625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [68.113, 36.77], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [107.57, 34.139], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.824, 0.824] },
                    o: { x: [0.167, 0.167], y: [0.176, 0.176] },
                    t: 4.171,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 9,
                    s: [110, 110],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.853, 0.853] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 77,
                    s: [110, 110],
                  },
                  { t: 81.0400390625, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [28.706, 34.26], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.99, 0.99], y: [1, 0.997] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 19,
                    s: [110, 110],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.842, 0.842] },
                    o: { x: [0.65, 0.65], y: [0, 0] },
                    t: 27,
                    s: [110, 110],
                  },
                  { t: 31.341796875, s: [0, 0] },
                ],
                ix: 3,
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 3,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 0,
      op: 88.421875,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
