export const inlineLoaderLightData = {
  v: "4.8.0",
  meta: { g: "LottieFiles AE 2.0.4", a: "", k: "", d: "", tc: "" },
  fr: 25,
  ip: 0,
  op: 214,
  w: 296,
  h: 112,
  nm: "_Loading_horizontal_dark",
  ddd: 0,
  assets: [],
  layers: [
    {
      ddd: 0,
      ind: 1,
      ty: 4,
      nm: "Layer 6 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [147.127, 61.768, 0], ix: 2 },
        a: { a: 0, k: [67.987, 38.897, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [4.31, 12.068],
                    [-8.516, -1.548],
                    [5.419, -3.678],
                    [6.774, 20.323],
                    [13.791, -10.665],
                  ],
                  o: [
                    [0, 0],
                    [-1.935, -5.419],
                    [8.516, 1.549],
                    [-5.42, 3.677],
                    [-7.146, -21.438],
                    [0, 0],
                  ],
                  v: [
                    [49.581, 7.268],
                    [9.258, -1.248],
                    [19.71, -13.442],
                    [22.42, 4.365],
                    [-17.064, 1.074],
                    [-49.581, -10.732],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.61], y: [1] },
                    o: { x: [0.85], y: [0] },
                    t: 187.195,
                    s: [0],
                  },
                  { t: 212.2197265625, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.16], y: [1] },
                    o: { x: [0.38], y: [0] },
                    t: 157.999,
                    s: [0],
                  },
                  { t: 183.0244140625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [67.081, 38.897], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [6.751, 36.271], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 157.999,
                    s: [0, 0],
                  },
                  { t: 162.169921875, s: [100, 100] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 157.1650390625,
      op: 214,
      st: 157.1650390625,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 2,
      ty: 4,
      nm: "Layer 3 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [146.324, 49.628, 0], ix: 2 },
        a: { a: 0, k: [68.326, 35.646, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [-6.97, -1.119],
                    [3.971, 8.237],
                    [-3.871, -13.211],
                    [-14.709, 1.775],
                    [-12.936, 0.387],
                    [-5.802, -5.015],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [24.129, 3.87],
                    [-3.742, -7.761],
                    [1.644, 5.608],
                    [18.568, -2.24],
                    [9.286, -0.278],
                    [8.251, 7.13],
                    [0, 0],
                  ],
                  v: [
                    [-49.758, 0.273],
                    [-38.758, 5.339],
                    [-15.403, -10.384],
                    [-29.339, -2.225],
                    [-9.984, 15.145],
                    [14.726, -7.371],
                    [29.12, 11.016],
                    [49.758, 15.145],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.6], y: [1] },
                    o: { x: [0.81], y: [0] },
                    t: 128.804,
                    s: [0],
                  },
                  { t: 153.828125, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.14], y: [1] },
                    o: { x: [0.41], y: [0] },
                    t: 100.442,
                    s: [0],
                  },
                  { t: 125.466796875, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [67.258, 35.645], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0, 5.669],
                    [-5.67, 0],
                    [0, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [130.732, 47.146], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 100.442,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 104.612,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 191.366,
                    s: [100, 100],
                  },
                  { t: 195.537109375, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 99.607421875,
      op: 195.537109375,
      st: 99.607421875,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 3,
      ty: 4,
      nm: "Layer 5 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [148.609, 53.612, 0], ix: 2 },
        a: { a: 0, k: [67.97, 41.759, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [7.735, -14.185],
                    [6.194, -29.066],
                    [-2.393, 13.096],
                    [0, 0],
                  ],
                  o: [
                    [0, 0],
                    [-14.838, 27.213],
                    [-3.652, 17.138],
                    [3.677, -20.129],
                    [0, 0],
                  ],
                  v: [
                    [49.47, -5.218],
                    [19.502, -10.074],
                    [-13.143, 7.121],
                    [-33.078, 3.797],
                    [-49.469, -12.377],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.59], y: [1] },
                    o: { x: [0.59], y: [0] },
                    t: 72.08,
                    s: [0],
                  },
                  { t: 97.10546875, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.15], y: [1] },
                    o: { x: [0.25], y: [0] },
                    t: 44.553,
                    s: [0],
                  },
                  { t: 68.7431640625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 2,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [68.97, 41.759], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [5.919, 31.382], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 44.553,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 48.723,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 132.14,
                    s: [100, 100],
                  },
                  { t: 136.3115234375, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 43.71875,
      op: 136.310546875,
      st: 44.552734375,
      bm: 0,
    },
    {
      ddd: 0,
      ind: 4,
      ty: 4,
      nm: "Layer 1 Outlines",
      sr: 1,
      ks: {
        o: { a: 0, k: 100, ix: 11 },
        r: { a: 0, k: 0, ix: 10 },
        p: { a: 0, k: [147.77, 57.554, 0], ix: 2 },
        a: { a: 0, k: [68.113, 36.77, 0], ix: 1 },
        s: { a: 0, k: [200, 200, 100], ix: 6 },
      },
      ao: 0,
      shapes: [
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, 0],
                    [-11.557, 15.79],
                    [-11.36, -8.516],
                    [-15.581, 9.368],
                  ],
                  o: [
                    [0, 0],
                    [12.317, -16.827],
                    [11.36, 8.516],
                    [0, 0],
                  ],
                  v: [
                    [-50.613, 6.319],
                    [-19.588, 3.48],
                    [19.419, -10.754],
                    [50.613, 5.31],
                  ],
                  c: false,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "st",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 3,
              },
              o: { a: 0, k: 100, ix: 4 },
              w: { a: 0, k: 7, ix: 5 },
              lc: 2,
              lj: 2,
              bm: 0,
              nm: "Stroke 1",
              mn: "ADBE Vector Graphic - Stroke",
              hd: false,
            },
            {
              ty: "tm",
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.59], y: [1] },
                    o: { x: [0.78], y: [0] },
                    t: 23,
                    s: [0],
                  },
                  { t: 41, s: [100] },
                ],
                ix: 1,
              },
              e: {
                a: 1,
                k: [
                  {
                    i: { x: [0.22], y: [1] },
                    o: { x: [0.6], y: [0] },
                    t: 2.503,
                    s: [0],
                  },
                  { t: 18.8291015625, s: [100] },
                ],
                ix: 2,
              },
              o: { a: 0, k: 0, ix: 3 },
              m: 1,
              ix: 3,
              nm: "Trim Paths 1",
              mn: "ADBE Vector Filter - Trim",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [68.113, 36.77], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: { a: 0, k: [100, 100], ix: 3 },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 1",
          np: 3,
          cix: 2,
          bm: 0,
          ix: 1,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.67, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [129.69, 36.25], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.167, 0.167], y: [0.167, 0.167] },
                    t: 4.171,
                    s: [0, 0],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [1, 1] },
                    o: { x: [0.167, 0.167], y: [0, 0] },
                    t: 8.342,
                    s: [100, 100],
                  },
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.61, 0.61], y: [0, 0] },
                    t: 76.869,
                    s: [100, 100],
                  },
                  { t: 81.0400390625, s: [0, 0] },
                ],
                ix: 3,
                x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Transform - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Transform - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Transform - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 2",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 2,
          mn: "ADBE Vector Group",
          hd: false,
        },
        {
          ty: "gr",
          it: [
            {
              ind: 0,
              ty: "sh",
              ix: 1,
              ks: {
                a: 0,
                k: {
                  i: [
                    [0, -3.131],
                    [3.131, 0],
                    [0, 3.131],
                    [-3.131, 0],
                  ],
                  o: [
                    [0, 3.131],
                    [-3.131, 0],
                    [0, -3.131],
                    [3.131, 0],
                  ],
                  v: [
                    [5.669, 0],
                    [0.001, 5.669],
                    [-5.669, 0],
                    [0.001, -5.669],
                  ],
                  c: true,
                },
                ix: 2,
              },
              nm: "Path 1",
              mn: "ADBE Vector Shape - Group",
              hd: false,
            },
            {
              ty: "fl",
              c: {
                a: 0,
                k: [0.16862745098, 0.16862745098, 0.172549019608, 1],
                ix: 4,
              },
              o: { a: 0, k: 100, ix: 5 },
              r: 1,
              bm: 0,
              nm: "Fill 1",
              mn: "ADBE Vector Graphic - Fill",
              hd: false,
            },
            {
              ty: "tr",
              p: { a: 0, k: [6.726, 36.25], ix: 2 },
              a: { a: 0, k: [0, 0], ix: 1 },
              s: {
                a: 1,
                k: [
                  {
                    i: { x: [0.833, 0.833], y: [0.833, 0.833] },
                    o: { x: [0.65, 0.65], y: [0, 0] },
                    t: 27.171,
                    s: [100, 100],
                  },
                  { t: 31.341796875, s: [0, 0] },
                ],
                ix: 3,
              },
              r: { a: 0, k: 0, ix: 6 },
              o: { a: 0, k: 100, ix: 7 },
              sk: { a: 0, k: 0, ix: 4 },
              sa: { a: 0, k: 0, ix: 5 },
              nm: "Transform",
            },
          ],
          nm: "Group 3",
          np: 2,
          cix: 2,
          bm: 0,
          ix: 3,
          mn: "ADBE Vector Group",
          hd: false,
        },
      ],
      ip: 0,
      op: 88.421875,
      st: 0,
      bm: 0,
    },
  ],
  markers: [],
};
