export const spinnerColorPrideData = {
  nm: "Spinner_color",
  h: 1000,
  w: 1000,
  meta: { g: "LottieFiles AE 2.0.4" },
  layers: [
    {
      ty: 0,
      nm: "_Spinner_color",
      sr: 1,
      st: 0,
      op: 161,
      ip: 0,
      hasMask: false,
      ao: 0,
      ks: {
        a: { a: 0, k: [500, 500, 0], ix: 1 },
        s: { a: 0, k: [100, 100, 100], ix: 6 },
        sk: { a: 0, k: 0 },
        p: { a: 0, k: [500, 500, 0], ix: 2 },
        r: { a: 0, k: 0, ix: 10 },
        sa: { a: 0, k: 0 },
        o: { a: 0, k: 100, ix: 11 },
      },
      ef: [],
      w: 1000,
      h: 1000,
      refId: "comp_0",
      tm: {
        a: 1,
        k: [
          {
            o: { x: 0.167, y: 0.167 },
            i: { x: 0.833, y: 0.833 },
            s: [0],
            t: 0,
          },
          { s: [6.44], t: 120 },
        ],
        ix: 2,
      },
      ind: 1,
    },
  ],
  v: "4.8.0",
  fr: 25,
  op: 120,
  ip: 0,
  assets: [
    {
      nm: "",
      id: "comp_0",
      layers: [
        {
          ty: 3,
          nm: "Null 4",
          sr: 1,
          st: -22,
          op: 139,
          ip: -22,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [500, 500, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [500, 500, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 0, ix: 11 },
          },
          ef: [],
          ind: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 8",
          sr: 1,
          st: 98,
          op: 139,
          ip: 98,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [151.516, 151.516], ix: 2 },
                },
                {
                  ty: "st",
                  nm: "Stroke 1",
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 24, ix: 5 },
                  c: { a: 0, k: [0.51, 0.094, 0.537], ix: 3 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, -0.008], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 2,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.36, y: 0 },
                    i: { x: 0.19, y: 1 },
                    s: [1],
                    t: 103,
                  },
                  { s: [51], t: 118 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 280, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.81, y: 0 },
                    i: { x: 0.75, y: 1 },
                    s: [1],
                    t: 123,
                  },
                  { s: [51], t: 138 },
                ],
                ix: 1,
              },
              m: 1,
            },
          ],
          ind: 2,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 6",
          sr: 1,
          st: 58,
          op: 98,
          ip: 58,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [151.516, 151.516], ix: 2 },
                },
                {
                  ty: "st",
                  nm: "Stroke 1",
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 24, ix: 5 },
                  c: { a: 0, k: [0.228, 0.024, 0.573], ix: 3 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, -0.008], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 2,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.36, y: 0 },
                    i: { x: 0.19, y: 1 },
                    s: [1.5],
                    t: 63,
                  },
                  { s: [69], t: 78 },
                ],
                ix: 2,
              },
              o: { a: 0, k: -23, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.81, y: 0 },
                    i: { x: 0.75, y: 1 },
                    s: [1.5],
                    t: 83,
                  },
                  { s: [69], t: 98 },
                ],
                ix: 1,
              },
              m: 1,
            },
          ],
          ind: 3,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 4",
          sr: 1,
          st: 18,
          op: 58,
          ip: 18,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [151.516, 151.516], ix: 2 },
                },
                {
                  ty: "st",
                  nm: "Stroke 1",
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 24, ix: 5 },
                  c: { a: 0, k: [0.337, 0.741, 0.749], ix: 3 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, -0.008], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 2,
              e: {
                a: 1,
                k: [
                  { o: { x: 0.36, y: 0 }, i: { x: 0.19, y: 1 }, s: [1], t: 23 },
                  { s: [53.5], t: 38 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 89, ix: 3 },
              s: {
                a: 1,
                k: [
                  { o: { x: 0.81, y: 0 }, i: { x: 0.75, y: 1 }, s: [1], t: 43 },
                  { s: [53.5], t: 58 },
                ],
                ix: 1,
              },
              m: 1,
            },
          ],
          ind: 4,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 10",
          sr: 1,
          st: 135,
          op: 175,
          ip: 135,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [151.516, 151.516], ix: 2 },
                },
                {
                  ty: "st",
                  nm: "Stroke 1",
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 24, ix: 5 },
                  c: { a: 0, k: [0.243, 0.549, 0.149], ix: 3 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, -0.008], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 2,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.36, y: 0 },
                    i: { x: 0.19, y: 1 },
                    s: [1],
                    t: 140,
                  },
                  { s: [65], t: 155 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 158, ix: 3 },
              s: {
                a: 1,
                k: [
                  {
                    o: { x: 0.81, y: 0 },
                    i: { x: 0.75, y: 1 },
                    s: [1],
                    t: 160,
                  },
                  { s: [65], t: 175 },
                ],
                ix: 1,
              },
              m: 1,
            },
          ],
          ind: 5,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 2",
          sr: 1,
          st: -22,
          op: 18,
          ip: -22,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [0, 0, 0], ix: 1 },
            s: { a: 0, k: [100, 100, 100], ix: 6 },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [0, 0, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [151.516, 151.516], ix: 2 },
                },
                {
                  ty: "st",
                  nm: "Stroke 1",
                  lc: 2,
                  lj: 1,
                  ml: 4,
                  o: { a: 0, k: 100, ix: 4 },
                  w: { a: 0, k: 24, ix: 5 },
                  c: { a: 0, k: [0.243, 0.549, 0.149], ix: 3 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [0, -0.008], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
            {
              ty: "tm",
              nm: "Trim Paths 1",
              ix: 2,
              e: {
                a: 1,
                k: [
                  {
                    o: { x: 0.36, y: 0 },
                    i: { x: 0.19, y: 1 },
                    s: [1],
                    t: -17,
                  },
                  { s: [65], t: -2 },
                ],
                ix: 2,
              },
              o: { a: 0, k: 158, ix: 3 },
              s: {
                a: 1,
                k: [
                  { o: { x: 0.81, y: 0 }, i: { x: 0.75, y: 1 }, s: [1], t: 3 },
                  { s: [65], t: 18 },
                ],
                ix: 1,
              },
              m: 1,
            },
          ],
          ind: 6,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 11",
          sr: 1,
          st: 140,
          op: 205,
          ip: 140,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.139 },
                  i: { x: 0.833, y: 0.861 },
                  s: [0, 0, 100],
                  t: 140,
                },
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [120, 120, 100],
                  t: 145,
                },
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.861 },
                  s: [120, 120, 100],
                  t: 200,
                },
                { s: [0, 0, 100], t: 205 },
              ],
              ix: 6,
              x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [67.145, -34.737, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [1, 1, 0.329], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 7,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 9",
          sr: 1,
          st: 103,
          op: 161,
          ip: 103,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.139 },
                  i: { x: 0.833, y: 0.861 },
                  s: [0, 0, 100],
                  t: 103,
                },
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [120, 120, 100],
                  t: 108,
                },
                {
                  o: { x: 0.167, y: 0 },
                  i: { x: 0.833, y: 1 },
                  s: [120, 120, 100],
                  t: 160,
                },
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.833 },
                  s: [100, 100, 100],
                  t: 163,
                },
                { s: [0, 0, 100], t: 168 },
              ],
              ix: 6,
              x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [56.707, 50.076, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [0.941, 0.58, 0.212], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 8,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 7",
          sr: 1,
          st: 63,
          op: 128,
          ip: 63,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.139 },
                  i: { x: 0.833, y: 0.861 },
                  s: [0, 0, 100],
                  t: 63,
                },
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [120, 120, 100],
                  t: 68,
                },
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.861 },
                  s: [120, 120, 100],
                  t: 123,
                },
                { s: [0, 0, 100], t: 128 },
              ],
              ix: 6,
              x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [-73.355, 20.763, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [0.918, 0.2, 0.137], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 9,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 5",
          sr: 1,
          st: 23,
          op: 88,
          ip: 23,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.139 },
                  i: { x: 0.833, y: 0.861 },
                  s: [0, 0, 100],
                  t: 23,
                },
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [120, 120, 100],
                  t: 28,
                },
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.861 },
                  s: [120, 120, 100],
                  t: 83,
                },
                { s: [0, 0, 100], t: 88 },
              ],
              ix: 6,
              x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [-57.355, -51.237, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [0.929, 0.435, 0.6], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 10,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 3",
          sr: 1,
          st: -17,
          op: 48,
          ip: -17,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.167, y: 0.139 },
                  i: { x: 0.833, y: 0.861 },
                  s: [0, 0, 100],
                  t: -17,
                },
                {
                  o: { x: 0.167, y: 0.167 },
                  i: { x: 0.833, y: 0.833 },
                  s: [120, 120, 100],
                  t: -12,
                },
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.861 },
                  s: [120, 120, 100],
                  t: 43,
                },
                { s: [0, 0, 100], t: 48 },
              ],
              ix: 6,
              x: "var $bm_rt;\nvar $bm_rt;\nvar amp, freq, decay, n, t, v;\ntry {\n    amp = div(effect('Scale - Overshoot')('ADBE Slider Control-0001'), 2.5), freq = div(effect('Scale - Bounce')('ADBE Slider Control-0001'), 20), decay = div(effect('Scale - Friction')('ADBE Slider Control-0001'), 20), n = 0, 0 < numKeys && (n = nearestKey(time).index, key(n).time > time && n--), t = 0 === n ? 0 : sub(time, key(n).time), $bm_rt = $bm_rt = 0 < n ? (v = velocityAtTime(sub(key(n).time, div(thisComp.frameDuration, 10))), add(value, div(mul(mul(div(v, 100), amp), Math.sin(mul(mul(mul(freq, t), 2), Math.PI))), Math.exp(mul(decay, t))))) : value;\n} catch (e$$4) {\n    $bm_rt = $bm_rt = value = value;\n}",
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [67.145, -34.737, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [1, 1, 0.329], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 11,
          parent: 1,
        },
        {
          ty: 4,
          nm: "Shape Layer 1",
          sr: 1,
          st: -22,
          op: 8,
          ip: -22,
          hasMask: false,
          ao: 0,
          ks: {
            a: { a: 0, k: [37.895, 50.263, 0], ix: 1 },
            s: {
              a: 1,
              k: [
                {
                  o: { x: 0.61, y: 0 },
                  i: { x: 0.833, y: 0.861 },
                  s: [120, 120, 100],
                  t: 3,
                },
                { s: [0, 0, 100], t: 8 },
              ],
              ix: 6,
            },
            sk: { a: 0, k: 0 },
            p: { a: 0, k: [56.645, 50.013, 0], ix: 2 },
            r: { a: 0, k: 0, ix: 10 },
            sa: { a: 0, k: 0 },
            o: { a: 0, k: 100, ix: 11 },
          },
          ef: [],
          shapes: [
            {
              ty: "gr",
              nm: "Ellipse 1",
              ix: 1,
              cix: 2,
              it: [
                {
                  ty: "el",
                  nm: "Ellipse Path 1",
                  d: 1,
                  p: { a: 0, k: [0, 0], ix: 3 },
                  s: { a: 0, k: [25.789, 25.789], ix: 2 },
                },
                {
                  ty: "fl",
                  nm: "Fill 1",
                  c: { a: 0, k: [0.941, 0.58, 0.212], ix: 4 },
                  r: 1,
                  o: { a: 0, k: 100, ix: 5 },
                },
                {
                  ty: "tr",
                  a: { a: 0, k: [0, 0], ix: 1 },
                  s: { a: 0, k: [100, 100], ix: 3 },
                  sk: { a: 0, k: 0, ix: 4 },
                  p: { a: 0, k: [37.895, 50.263], ix: 2 },
                  r: { a: 0, k: 0, ix: 6 },
                  sa: { a: 0, k: 0, ix: 5 },
                  o: { a: 0, k: 100, ix: 7 },
                },
              ],
            },
          ],
          ind: 12,
          parent: 1,
        },
      ],
    },
  ],
};
