name: Slack Notify
description: Sends a Slack notification
inputs:
  repo:
    description: The repository name
    required: true
  tag_name:
    description: The release tag name
    required: true
  body:
    description: The release body
    required: true
  webhook_url:
    description: The Slack webhook URL
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack Notification
      shell: bash
      run: |
        version=$(echo '${{ inputs.body }}' | jq -r '.[] | select(.name=="@vygruppen/spor-react") | .version')
        if [ -z "$version" ]; then
          echo "No @vygruppen/spor-react version found in the body. Skipping notification."
          exit 0
        fi
        encoded_version=$(echo "@vygruppen/spor-react@$version" | jq -sRr @uri)
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"*Ny versjon av spor er ute!* 📦✨ \n
          ⚡️ *Versjon*: v${version} \n
          📖 *Changelog*: <https://github.com/nsbno/spor/releases/tag/${encoded_version}|${encoded_version}> \n
          📦 *Installer*: \`npm i @vygruppen/spor-react@latest\` \n \"
        }" ${{ inputs.webhook_url }}
