name: Slack Notify
description: Sends a Slack notification
inputs:
  repo:
    description: The repository name
    required: true
  tag_name:
    description: The release tag name
    required: true
  body:
    description: The release body
    required: true
  webhook_url:
    description: The Slack webhook URL
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Slack Notification
      shell: bash
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"*Ny versjon av spor er ute!* 📦✨ \n
          📖 *Changelog*: <https://github.com/${{ inputs.repo }}/releases/tag/${{ inputs.tag_name }}|${{ inputs.tag_name }}> \n
          📦 *Installer*: \`npm i @vygruppen/spor-react@latest\` \n
          📝 *Details*: ${{ inputs.body }} \"
        }" ${{ inputs.webhook_url }}
