import { Button, Input as ChakraInput, useDisclosure } from "@chakra-ui/react";
import React, { useId, forwardRef } from "react";
import { InputLeftElement, InputProps, InputRightElement } from ".";
import { createTexts, useTranslation } from "..";
import { Field } from "../components/ui/field";
import { InputGroup } from "../components/ui/input-group";

export type PasswordInputProps = Omit<InputProps, "isDisabled"> & {
  isDisabled?: boolean;
};
export const PasswordInput = forwardRef<HTMLInputElement, PasswordInputProps>(
  (props, ref) => {
    const { open: isShowingPassword, onToggle } = useDisclosure();
    const { t } = useTranslation();
    const autoGeneratedId = `password-input-${useId()}`;
    const inputId = props.id ?? props?.id ?? autoGeneratedId;
    return (
      <InputGroup position="relative">
        <>
          {props.leftIcon && (
            <InputLeftElement>{props.leftIcon}</InputLeftElement>
          )}
          <Field label={props.label}>
            <ChakraInput
              {...props}
              id={inputId}
              placeholder=" " // This is needed to make the label work as expected
              type={isShowingPassword ? "text" : "password"}
              paddingRight={10}
              paddingLeft={props.leftIcon ? 7 : undefined}
              ref={ref}
              data-attachable
            />
          </Field>
          <InputRightElement width="fit-content">
            <Button
              variant="ghost"
              type="button"
              fontWeight="normal"
              size="sm"
              onClick={onToggle}
              borderRadius="sm"
              marginRight={1}
              disabled={props.disabled || props.isDisabled}
            >
              {isShowingPassword
                ? t(texts.hidePassword)
                : t(texts.showPassword)}
            </Button>
          </InputRightElement>
        </>
      </InputGroup>
    );
  },
);

const texts = createTexts({
  showPassword: {
    nb: "Vis",
    nn: "Vis",
    en: "Show",
    sv: "Visa",
  },
  hidePassword: {
    nb: "Skjul",
    nn: "Skjul",
    en: "Hide",
    sv: "Dölj",
  },
});
