import {
  Button,
  Input as ChakraInput,
  forwardRef,
  useDisclosure,
  useFormControlContext,
} from "@chakra-ui/react";
import React, { useId } from "react";
import {
  FormLabel,
  InputGroup,
  InputLeftElement,
  InputProps,
  InputRightElement,
} from ".";
import { createTexts, useTranslation } from "..";

export type PasswordInputProps = InputProps;
export const PasswordInput = forwardRef<PasswordInputProps, "input">(
  ({ leftIcon, id, label, size, ...props }, ref) => {
    const { isOpen: isShowingPassword, onToggle } = useDisclosure();
    const { t } = useTranslation();
    const formControlProps = useFormControlContext();
    const autoGeneratedId = `password-input-${useId()}`;
    const inputId = id ?? formControlProps?.id ?? autoGeneratedId;
    return (
      <InputGroup position="relative">
        {leftIcon && <InputLeftElement>{leftIcon}</InputLeftElement>}
        <ChakraInput
          {...props}
          id={inputId}
          placeholder=" " // This is needed to make the label work as expected
          type={isShowingPassword ? "text" : "password"}
          paddingRight={10}
          paddingLeft={leftIcon ? 7 : undefined}
          ref={ref}
          data-attachable
        />
        <FormLabel htmlFor={inputId} pointerEvents="none">
          {label}
        </FormLabel>
        <InputRightElement width="fit-content">
          <Button
            variant="ghost"
            type="button"
            onClick={onToggle}
            borderRadius="sm"
            marginRight={1}
            isDisabled={props.disabled || props.isDisabled}
          >
            {isShowingPassword ? t(texts.hidePassword) : t(texts.showPassword)}
          </Button>
        </InputRightElement>
      </InputGroup>
    );
  },
);

const texts = createTexts({
  showPassword: {
    nb: "Vis",
    nn: "Vis",
    en: "Show",
    sv: "Visa",
  },
  hidePassword: {
    nb: "Skjul",
    nn: "Skjul",
    en: "Hide",
    sv: "Dölj",
  },
});
