module.exports = {
  extends: ["next", "prettier"],
  settings: {
    next: {
      rootDir: [
        "apps/docs/",
        "packages/config/",
        "packages/tsconfig/",
        "packages/spor-theme-react/",
        "packages/spor-react/",
        "packages/spor-logo-react/",
        "packages/spor-input-react/",
        "packages/spor-i18n-react/",
        "packages/spor-button-react/",
        "packages/spor-layout-react/",
        "packages/spor-typography-react/",
        "packages/spor-icon/",
        "packages/spor-icon-react/",
        "packages/spor-image-react/",
        "packages/spor-card-react/",
        "packages/spor-modal-react/",
        "packages/spor-table-react/",
        "packages/spor-accordion-react/",
        "packages/spor-design-tokens/",
        "packages/spor-link-react/",
        "packages/spor-stepper-react/",
        "packages/spor-popover-react/",
        "packages/spor-tab-react/",
        "packages/spor-provider-react/",
        "packages/spor-theme-react-native/",
        "packages/spor-provider-react-native/",
        "packages/spor-react-native/",
        "packages/spor-typography-react-native/",
        "packages/spor-button-react-native/",
        "packages/spor-layout-react-native/",
        "packages/spor-loader-react/",
        "packages/spor-loader/",
        "packages/spor-loader-react-native/",
        "packages/spor-card-react-native/",
        "packages/spor-icon-react-native/",
        "packages/spor-badge-react-native/",
        "packages/spor-accordion-react-native/",
      ],
    },
  },
};
