name: Continuous Integration

on:
  pull_request:
    branches: [main] # Change to main when update-chakra is merged

jobs:
  build:
    name: "CI - build validation"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint
      - run: pnpm build --filter=./apps/design-studio"
      - run: pnpm test
      - run: pnpm format:validate
