name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: "CI - build validation"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: pnpm format:validate
      - name: Notify Slack on New Releass
        uses: ./.github/workflows/slack-notify.yml
        with:
          repo: ${{ github.repository }}
          tag_name: ${{ github.ref_name }}
          body: "Body 123 content"
