name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: "CI - build validation"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Notify Slack
        uses: ./.github/actions/slack-notify
        with:
          repo: ${{ github.repository }}
          published_packages: '[{"name":"@vygruppen/spor-loader","version":"0.5.0"}, {"name":"@vygruppen/spor-react","version":"11.3.3"}]'
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test
      - run: pnpm format:validate
